'use strict';
const $ = (selector, root=document) => root.querySelector(selector);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
 network:'M12 3 3 8l9 5 9-5-9-5ZM3 12l9 5 9-5M3 16l9 5 9-5',
 overview:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',
 board:'M3 4h18v16H3zM9 4v16M15 4v16M5 8h2M11 8h2M17 8h2M5 12h2M11 12h2',
 game:'M7 7h10l4 11-3 2-4-4h-4l-4 4-3-2L7 7ZM6 11h6M9 8v6M16 10h.01M18 13h.01',
 room:'M3 8l9-5 9 5v12H3V8ZM7 20V9h10v11M3 8h18M10 13h4M12 11v4',
 scan:'M3 8V3h5M16 3h5v5M21 16v5h-5M8 21H3v-5M6 12h12M12 6v12',
 bear:'M7 7a3 3 0 1 1-4 3M17 7a3 3 0 1 0 4 3M5 12a7 7 0 1 1 14 0v3a7 6 0 0 1-14 0v-3ZM9 11h.01M15 11h.01M10 15h4l-2 2-2-2Z',
 layers:'M12 3 3 8l9 5 9-5-9-5ZM3 12l9 5 9-5M3 16l9 5 9-5',
 eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12ZM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
 image:'M3 3h18v18H3zM3 17l6-6 4 4 3-3 5 5M16 7h.01',
 book:'M3 4h7l2 2 2-2h7v16h-7l-2 1-2-1H3V4ZM12 6v15M6 8h3M15 8h3',
 activity:'M3 12h4l3-8 4 16 3-8h4',
 refresh:'M20 7v5h-5M4 17v-5h5M6 7a7 7 0 0 1 12-2l2 3M4 16l2 3a7 7 0 0 0 12-2',
 external:'M14 3h7v7M21 3l-10 10M10 3H3v18h18v-7',
 close:'M5 5l14 14M19 5 5 19',
 check:'M20 12a8 8 0 1 1-4-7M8 11l4 4 9-11',
 help:'M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0ZM9 9a3 3 0 0 1 6 0c0 2-3 2-3 4M12 16h.01',
 lock:'M6 10h12v11H6zM8 10V6a4 4 0 0 1 8 0v4M12 14v3',
 arrow:'M4 12h16M14 6l6 6-6 6',
 clock:'M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0ZM12 7v5l3 2',
 file:'M5 2h9l5 5v15H5V2ZM14 2v6h5M8 12h8M8 16h8',
 download:'M12 3v12M7 10l5 5 5-5M4 15v6h16v-6',
 edit:'M4 16 16 4l4 4L8 20H4v-4ZM13 7l4 4',
 copy:'M8 8h13v13H8zM16 8V3H3v13h5',
 branch:'M6 3v14a3 3 0 1 0 0 6M6 13c0-7 12 0 12-7V3M4 3h4M16 3h4',
 shield:'M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3ZM8 12l3 3 5-6'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.file}"/></svg>`;
const names = {overview:'Overview',agents:'Agent build',work:'Work board',federation:'Federation',assets:'Assets & references',evidence:'Evidence & gates',runbooks:'Runbooks',activity:'Activity'};
const symbols = {overview:'overview',agents:'branch',work:'board',federation:'network',assets:'image',evidence:'eye',runbooks:'book',activity:'activity'};
const descriptions = {overview:'Game development and the workspace that supports it.',agents:'Focused assignments, source identity and reviewable handoffs for LLM-assisted development.',work:'Scope, ownership, dependencies and evidence for both development tracks.',federation:'Independent sources, explicit authority and timestamped local inspection.',assets:'Distinguish visual direction, source identity and candidate evidence.',evidence:'Verification, interpretation and acceptance retain separate gates.',runbooks:'Known entry points, prerequisites and expected outputs.',activity:'Durable work records and observations against a named source snapshot.'};
const labels = {ready:'Ready',active:'In progress',blocked:'Blocked',review:'In review',done:'Complete',verified:'Identity verified',observed:'Observed',unbound:'Unbound',missing:'Missing',unavailable:'Unavailable',changed:'Identity changed','identity-mismatch':'Different identity',unresolved:'Unresolved',pending:'Not recorded'};
let sourceRead=0;
let data, writeToken, active='overview', filters={track:'all',status:'all',query:'',module:'all'}, returnFocus;
let selectedAgentTask, preparedPacket, agentTrack='game', packetBusy=false;
const dialog=$('#dialog');
const stamp=value=>new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Johannesburg'}).format(new Date(value));
const badge=(state,text)=>`<span class="badge ${esc(state)}">${icon(['verified','done'].includes(state)?'check':['blocked','unresolved','changed','missing','unavailable','identity-mismatch'].includes(state)?'help':'clock')}${esc(text||labels[state]||state)}</span>`;
const moduleFor=id=>data.catalog.modules.find(m=>m.id===id);
const artifact=id=>data.snapshot.artifacts.find(a=>a.id===id);
const sourceButton=(id,label='Read source')=>`<button class="text-button" data-read="${esc(id)}">${esc(label)} ${icon('external')}</button>`;
const notice=(title,text)=>`<div class="notice">${icon('shield')}<div><strong>${esc(title)}</strong><p>${esc(text)}</p></div></div>`;

async function request(path,body){
  const options=body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Workspace-Token':writeToken},body:JSON.stringify(body)};
  const response=await fetch(path,options);
  const result=await response.json();
  if(!response.ok)throw new Error(result.error||`Request failed (${response.status})`);
  return result;
}
function toast(message){const t=$('.toast');t.textContent=message;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,4500);}
function error(message){$('#error').textContent=message;$('#error').hidden=!message;}
async function load(){const value=await request('/api/workspace');writeToken=value.writeToken;delete value.writeToken;data=value;render();}
function route(){const key=location.hash.slice(1).split('/')[0];active=key in names?key:'overview';if(data){const nav=document.activeElement?.closest('#navigation a')?.getAttribute('href');render();if(nav)$('#navigation a[href="'+nav+'"]')?.focus();}}
function modal(title,html){sourceRead++;returnFocus=document.activeElement;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=html;if(!dialog.open)dialog.showModal();}
function close(){sourceRead++;dialog.close();if(returnFocus?.isConnected)returnFocus.focus();else $('#main').focus();}

function gates(){return `<div class="gate-grid">${data.catalog.gates.map(g=>{const a=artifact(g.source),valid=['observed','verified'].includes(a?.state),state=!valid?'unavailable':g.status==='Recorded pass'?'verified':g.status==='Unresolved'?'unresolved':'pending';return `<article class="gate"><h3>${esc(g.label)}</h3>${badge(state,valid?g.status:'Source unavailable')}<p>${esc(g.scope)}</p>${sourceButton(g.source)}</article>`;}).join('')}</div>`;}
function services(){return data.snapshot.services.map(s=>`<div class="service"><div><strong>${esc(s.name)}</strong><small>${esc(s.url)}</small><small>Checked ${esc(stamp(s.observedAt))}</small></div><div>${badge(s.state,s.state==='verified'?'Connected':null)}<p><a class="text-button" href="${esc(s.url)}" target="_blank" rel="noopener">Open ${icon('external')}</a> · <button class="text-button" data-runbook="${esc(s.runbook)}">Runbook</button></p></div></div>`).join('');}
function track(track,title,text){const items=data.work.filter(w=>w.track===track);return `<article class="card"><header><span class="item-icon">${icon(track==='game'?'game':'network')}</span><div><h3>${title}</h3><small>${track==='game'?'Encounter, chamber and character':'Tools, federation and review'}</small></div></header><p>${text}</p><div class="track-summary"><span><strong>${items.filter(w=>w.status==='active').length}</strong>in progress</span><span><strong>${items.filter(w=>w.status==='blocked'||w.blockedBy.length).length}</strong>with blockers</span><span><strong>${items.filter(w=>w.status==='done').length}</strong>complete</span></div><button class="text-button" data-track="${track}">Open ${title.toLowerCase()} work ${icon('arrow')}</button></article>`;}
function overview(){const available=data.snapshot.members.filter(m=>m.state==='observed').length;return `<div class="hero"><div class="hero-copy"><p class="eyebrow">ONE WORKSPACE · TWO DEVELOPMENT TRACKS</p><h2>Build the encounter.<br>Keep the evidence connected.</h2><p>The chamber, scanned character and playable game retain their own sources. Work moves forward through measured experiments, saved results and explicit review.</p><div class="actions"><a class="button primary" href="#work">Open work board ${icon('arrow')}</a><a class="button" href="#federation">Inspect federation</a></div><div class="scope">${icon('lock')}Local coordination · source ownership retained</div></div><figure><img src="/artifact/target-front" alt="Selected full-chamber concept: enclosed industrial room, teal overhead light and teddy encounter"><figcaption><span>Selected chamber direction</span><span>Reference concept · not runtime</span></figcaption></figure></div>
<div class="metrics"><div class="metric"><p>${icon('network')}Connected members</p><strong>${available} / ${data.snapshot.members.length}</strong><small>Source locations observed</small></div><div class="metric"><p>${icon('layers')}Development modules</p><strong>${data.catalog.modules.length}</strong><small>Explicit authority and dependencies</small></div><div class="metric"><p>${icon('board')}Open work items</p><strong>${data.work.filter(x=>x.status!=='done').length}</strong><small>Game + workspace tracks</small></div><div class="metric"><p>${icon('eye')}Catalogued artifacts</p><strong>${data.snapshot.artifacts.length}</strong><small>Identity and scope attached</small></div></div>
<div class="grid-2">${track('game','Game development','Contact ownership is the next character checkpoint. Chamber refinement and encounter validation can progress through their own scoped baselines.')}${track('workspace','Workspace development','The scaffold connects sources, work records, tools and evidence. Extend it alongside actual game deliverables.')}</div>
<div class="section-heading"><h2>Independent review gates</h2><a href="#evidence">Inspect evidence ${icon('arrow')}</a></div>${gates()}
<div class="section-heading"><h2>Working connections</h2><a href="#runbooks">All runbooks ${icon('arrow')}</a></div><div class="grid-2"><article class="card service-list">${services()}</article><article class="card"><header><span class="item-icon">${icon('bear')}</span><h3>Next character experiment</h3></header><p>Compare conservative contact alternatives against the frozen V2 map. Preserve genuine body volume, record exact face selections, and keep unsupported anatomy unresolved.</p><div class="actions">${sourceButton('contact-protocol','Read the protocol')}<button class="text-button" data-task="GAME-001">View work item ${icon('arrow')}</button></div></article></div>`;}
function taskCard(w){return `<article class="task"><div class="task-top"><span class="task-id">${esc(w.id)} · ${esc(w.priority)}</span>${badge(w.status)}</div><h3>${esc(w.title)}</h3><p>${esc(w.question)}</p>${w.blockedBy.length?`<p class="blocked">${icon('lock')}Depends on ${esc(w.blockedBy.join(', '))}</p>`:''}<div class="meta">${esc(moduleFor(w.module).name)}<br>Owner: ${esc(w.owner)}</div><footer><span>${esc(w.track)} · revision ${w.revision}</span><button class="text-button" data-task="${esc(w.id)}">Review work ${icon('arrow')}</button></footer></article>`;}
function work(){const items=data.work.filter(w=>(filters.track==='all'||w.track===filters.track)&&(filters.status==='all'||w.status===filters.status)&&`${w.id} ${w.title} ${w.question} ${w.owner}`.toLowerCase().includes(filters.query.toLowerCase()));return `<div class="filters"><label class="field">Track<select id="track-filter">${[['all','All tracks'],['game','Game development'],['workspace','Workspace development']].map(([v,l])=>`<option value="${v}" ${filters.track===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="field">Workflow status<select id="status-filter">${['all','ready','active','blocked','review','done'].map(v=>`<option value="${v}" ${filters.status===v?'selected':''}>${v==='all'?'All statuses':labels[v]}</option>`).join('')}</select></label><label class="field search">Search work<input id="work-search" type="search" value="${esc(filters.query)}" placeholder="ID, question, owner or title"></label></div><p class="small">${items.length} work items · Dependencies apply before work can enter progress, review or completion.</p><div class="section-heading"><h2>${filters.track==='all'?'Both development tracks':filters.track==='game'?'Game development':'Workspace development'}</h2><span class="small">Completion records workflow, not acceptance.</span></div><div class="board">${items.map(taskCard).join('')||'<p class="empty">No work matches these filters.</p>'}</div>`;}
function federation(){return `<div class="flow" aria-label="Development flow"><div>${icon('scan')}<strong>Capture & sources</strong><small>Scanner · reference archive</small></div><div>${icon('bear')}<strong>Character & Studio</strong><small>Identity · deformation · inspection</small></div><div>${icon('game')}<strong>Native encounter</strong><small>Chamber · gameplay · delivery</small></div><div>${icon('eye')}<strong>Evidence & decisions</strong><small>Measure · save · decide</small></div></div>${notice('Federation preserves source authority','The hub reads connected members and records its own work journal. Branches are not merged; remote synchronization and current lock ownership are not inferred.')}<div class="grid-2">${data.catalog.modules.map(m=>{const member=data.snapshot.members.find(x=>x.id===m.member);return `<article class="card member-card"><header><span class="item-icon">${icon(m.icon)}</span><div><h3>${esc(m.name)}</h3><small>${esc(m.kind)} · ${esc(m.ownerRole)}</small></div>${badge(member.state)}</header><p>${esc(m.focus)}</p><dl class="detail-list"><div><dt>Authority</dt><dd>${esc(m.authority)}</dd></div><div><dt>Bound source</dt><dd class="path">${esc(member.path||'Not bound on this machine')}</dd></div>${member.git?`<div><dt>Local Git observation</dt><dd>${esc(member.git.branch||'Unavailable')} · ${esc(member.git.head?.slice(0,10)||'unknown')}<br>${member.git.localChangeEntries??'Unknown'} local change entries · remote not fetched</dd></div>`:''}<div><dt>Write boundary</dt><dd>${esc(m.writePolicy)}</dd></div></dl><div class="dependencies">${m.dependencies.map(id=>`<span>Depends on ${esc(moduleFor(id).name)}</span>`).join('')||'<span>No module dependency</span>'}</div><footer><span>Observed ${esc(stamp(member.observedAt))}</span><button class="text-button" data-module="${esc(m.id)}">Module evidence ${icon('arrow')}</button></footer></article>`;}).join('')}</div>`;}
function assets(){const records=data.snapshot.artifacts.filter(a=>['image','identity'].includes(a.kind));return `<div class="grid-3">${records.map(a=>`<article class="card asset">${a.kind==='image'&&['observed','verified'].includes(a.state)?`<a href="${esc(a.href)}" target="_blank" rel="noopener"><img src="${esc(a.href)}" alt="${esc(a.title)}" loading="lazy"></a>`:`<div class="asset-icon">${icon(a.kind==='image'?'image':'scan')}</div>`}<div class="asset-body"><span class="eyebrow">${esc(a.classification)}</span><h3>${esc(a.title)}</h3><p>${esc(a.scope)}</p><footer>${badge(a.state)}<button class="text-button" data-read="${esc(a.id)}">Identity ${icon('external')}</button></footer></div></article>`).join('')}</div>${notice('Reference, source and runtime are different records','Concepts establish direction. The original scan establishes visible identity. A saved candidate capture demonstrates that revision only; none of these automatically supplies visual acceptance.')}`;}
function evidence(){const records=data.snapshot.artifacts.filter(a=>!['image','identity'].includes(a.kind)&&(filters.module==='all'||a.module===filters.module));return `${gates()}<div class="section-heading"><h2>Source records</h2><label class="field">Module<select id="module-filter"><option value="all">All modules</option>${data.catalog.modules.map(m=>`<option value="${esc(m.id)}" ${m.id===filters.module?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label></div><div class="artifact-list">${records.map(a=>`<article class="artifact-row"><span class="item-icon">${icon('file')}</span><div><h3>${esc(a.title)}</h3><p>${esc(a.scope)}</p><small>${esc(a.classification)} · ${esc(moduleFor(a.module).name)}</small></div><div class="actions">${badge(a.state)}${sourceButton(a.id)}</div></article>`).join('')||'<p class="empty">No text records are catalogued for this module. See Assets & references for source imagery.</p>'}</div>`;}
function runbookCard(r){return `<article class="card runbook"><header><span class="item-icon">${icon(moduleFor(r.module).icon)}</span><div><h3>${esc(r.title)}</h3><small>${esc(moduleFor(r.module).name)}</small></div></header><pre>${esc(r.command)}</pre><strong class="small">Prerequisites</strong><ul>${r.prerequisites.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><p class="produces"><strong>Expected output:</strong> ${esc(r.produces)}</p><footer><span>Deliberate local execution</span><button class="text-button" data-copy="${esc(r.id)}">Copy command ${icon('copy')}</button></footer></article>`;}
function runbooks(){return `${notice('Commands are inspection and launch entry points','Review the member location and prerequisites before execution. The workspace does not start Unreal, modify locks or run shell commands from a browser request.')}<div class="grid-2">${data.catalog.runbooks.map(runbookCard).join('')}</div>`;}
function activity(){return `<div class="section-heading"><h2>Work journal</h2><button class="button primary" id="add-observation">${icon('edit')}Record observation</button></div><p class="small">${data.events.length} persistent events · observations retain their inspection snapshot.</p><div class="timeline">${data.events.map(e=>{const p=e.payload;return `<article class="event"><header><h3>${esc(e.kind==='observation'?p.title:e.entity_id+' · '+e.kind.replaceAll('-',' '))}</h3><small>${esc(stamp(e.at))}</small></header><p>${esc(e.kind==='observation'?p.observation:e.kind==='work-updated'?p.after.rationale:p.title||p.result?.summary||p.reason||p.owner||'Agent workflow record')}</p>${e.kind==='work-updated'?`<p>${esc(labels[p.before.status])} → ${esc(labels[p.after.status])} · ${esc(p.after.owner)}</p>`:''}${e.kind==='observation'?`<p><strong>Limitations:</strong> ${esc(p.limitations)}<br><strong>Next evidence:</strong> ${esc(p.nextEvidence)}</p><small>${esc(p.author)} · ${esc(p.snapshotId)}</small>`:''}<details><summary>Event record · ${e.sequence}</summary><pre>${esc(JSON.stringify(e,null,2))}</pre></details></article>`;}).join('')}</div>`;}
function render(){error('');$('#navigation').innerHTML=Object.entries(names).map(([key,label])=>`<a href="#${key}" ${key===active?'aria-current="page"':''}>${icon(symbols[key])}${label}</a>`).join('');$('#crumb').textContent=names[active];$('#title').textContent=active==='overview'?'Workspace overview':names[active];$('#description').textContent=descriptions[active];$('#kicker').textContent=active==='work'?'GAME + WORKSPACE':active==='agents'?'LLM DEVELOPMENT CONTROL':'HORROR GAME · LOCAL FEDERATION';$('#stamp').textContent='Inspected '+stamp(data.snapshot.observedAt)+' SAST';$('#identity').textContent=data.snapshot.id+' · '+data.catalog.id;$('#content').innerHTML=({overview,agents,work,federation,assets,evidence,runbooks,activity}[active])();}

function agents(){
 const queue=data.agents, tasks=queue.tasks.filter(t=>t.track===agentTrack);
 let task=tasks.find(t=>t.id===selectedAgentTask)||tasks.find(t=>t.eligible)||tasks.find(t=>t.status==='active')||tasks.find(t=>t.status!=='done')||tasks[0];
 selectedAgentTask=task.id;const c=task.contract;
 const runs=queue.runs.filter(r=>r.state==='active');
 return `<div class="agent-intro"><div><span class="eyebrow">ONE TASK · EXPLICIT SCOPE · SAVED EVIDENCE</span><h2>Prepare the work.<br>Keep the evidence attached.</h2><p>Give your coding agent a focused assignment with exact sources, write boundaries and a structured return path.</p></div><div class="agent-loop"><span>${icon('file')}Prepare context</span><span>${icon('lock')}Reserve scope</span><span>${icon('branch')}Build & verify</span><span>${icon('eye')}Hand off for review</span></div></div>
 <div class="agent-layout"><article class="card agent-assignment"><header><span class="item-icon">${icon('board')}</span><div><h3>Build assignment</h3><small>Model-neutral · existing local tools</small></div></header><div class="filters"><label class="field">Development track<select id="agent-track"><option value="game" ${agentTrack==='game'?'selected':''}>Game development</option><option value="workspace" ${agentTrack==='workspace'?'selected':''}>Workspace development</option></select></label><label class="field agent-task-field">Task<select id="agent-task">${tasks.map(t=>`<option value="${esc(t.id)}" ${t.id===task.id?'selected':''}>${esc(t.id+' · '+t.title)}</option>`).join('')}</select></label></div><div class="task-top"><span class="task-id">${esc(task.id)} · ${esc(task.priority)} · revision ${task.revision}</span>${badge(task.eligible?'ready':'blocked',task.eligible?'Available to reserve':'Not ready to reserve')}</div><h3>${esc(task.title)}</h3><p class="agent-next">${esc(task.nextAction)}</p>${task.reasons.length?notice('Resolve before starting',task.reasons.join(' ')):''}<dl class="detail-list"><div><dt>Write member</dt><dd>${esc(c.member)} · ${esc(data.snapshot.members.find(m=>m.id===c.member)?.path||'Unbound')}</dd></div><div><dt>Permitted output paths</dt><dd class="scope-paths">${c.writePaths.map(p=>`<code>${esc(p)}</code>`).join('')}</dd></div><div><dt>Execution requirements</dt><dd><ul>${c.requirements.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></dd></div></dl><div class="packet-controls"><label class="field">Prompt size limit<select id="agent-budget"><option value="24000">24,000 characters</option><option value="40000">40,000 characters</option><option value="64000">64,000 characters</option></select></label><button class="button primary" id="prepare-packet">${icon('file')}Prepare context packet</button></div><p class="small">Saves local context only. Preparation does not reserve work or launch a model.</p></article>
 <div class="agent-side"><article class="card"><header><span class="item-icon">${icon('shield')}</span><h3>Reliable handoffs</h3></header><ul class="criteria"><li>Dependencies and overlapping reservations checked.</li><li>Required instructions kept in full; excerpts labelled.</li><li>Exact source and output hashes recorded.</li><li>Technical findings and acceptance remain separate.</li></ul><button class="text-button" data-read="agent-guide">Read the agent workflow ${icon('arrow')}</button></article><article class="card"><header><span class="item-icon">${icon('lock')}</span><h3>Active reservations <span class="small">${runs.length}</span></h3></header>${runs.map(r=>`<div class="agent-run"><strong>${esc(r.task)} · ${esc(r.owner)}</strong><small>${esc(r.id)}</small><p>Reserved ${esc(stamp(r.created_at))}</p><button class="text-button" data-agent-run="${esc(r.id)}">Resume / release instructions ${icon('arrow')}</button></div>`).join('')||'<p>No scope is currently reserved.</p>'}<p class="small">Reservations coordinate participating agents. Git LFS locks and session permissions still apply.</p></article></div></div>
 <div class="section-heading"><h2>Recent handoffs</h2><a href="#activity">Full journal ${icon('arrow')}</a></div><div class="grid-2">${queue.runs.filter(r=>r.result).slice(0,6).map(r=>`<article class="card"><div class="task-top"><span class="task-id">${esc(r.task)}</span>${badge(r.state)}</div><h3>${esc(r.result.result.summary)}</h3><p>${esc(r.result.result.limitations)}</p><button class="text-button" data-agent-run="${esc(r.id)}">Read handoff ${icon('arrow')}</button></article>`).join('')||'<p class="empty">No agent handoffs yet. Finished work enters review with its evidence; it never auto-approves a game asset.</p>'}</div>`;
}

async function preparePacket(){
 if(packetBusy)return;packetBusy=true;const button=$('#prepare-packet');button.disabled=true;
 try{const p=await request('/api/agent/packet',{taskId:selectedAgentTask,budgetCharacters:Number($('#agent-budget').value)});preparedPacket=p;await load();showPacket(p);
 }catch(e){error(e.message);}finally{packetBusy=false;button.disabled=false;}
}
function showPacket(p){
 modal('Context packet · '+p.task.id,`<div class="packet-stats"><div><strong>${p.contextCharacters.toLocaleString()}</strong><small>prompt characters</small></div><div><strong>${p.sources.length}</strong><small>identified sources</small></div><div><strong>${p.sources.filter(s=>s.inclusion.startsWith('excerpt')||s.inclusion==='reference only').length}</strong><small>references / excerpts</small></div></div><p class="small">This is a measured character count, not a model token estimate. Instructions are full; source files keep their complete SHA-256 identities.</p><dl class="detail-list"><div><dt>Packet ID</dt><dd class="path">${esc(p.id)}</dd></div><div><dt>Saved prompt</dt><dd class="path">workspace/local/agent-packets/${esc(p.id)}.md</dd></div></dl><div class="actions"><button class="button primary" id="packet-prompt">Read / copy prompt</button><button class="button" id="packet-json">Structured JSON</button><button class="button" id="packet-template">Result template</button></div><h3 class="section-heading">Begin in your coding-agent session</h3><pre class="agent-command">python tools/workspace.py agent start ${esc(p.id)} --owner "Your session label"</pre><p class="small">Run from the integration checkout. The reservation rechecks task revision, source identities, dependencies and conflicts.</p><div class="artifact-list">${p.sources.map(s=>`<div class="packet-source"><strong>${esc(s.member+':'+s.path)}</strong><span>${esc(s.inclusion)}</span></div>`).join('')}</div>`);
}
async function packetText(kind){
 const p=preparedPacket;if(!p)return;
 // Markdown comes from the same saved packet, never reconstructed in the browser.
 let text,title;
 if(kind==='prompt'){const r=await fetch('/api/agent/prompt/'+encodeURIComponent(p.id));if(!r.ok)throw new Error((await r.json()).error);text=await r.text();title='Saved build prompt';}
 else if(kind==='template'){const r=await request('/api/agent/template/'+encodeURIComponent(p.id));text=JSON.stringify(r,null,2);title='Result template';}
 else{text=JSON.stringify(p,null,2);title='Structured context packet';}
 modal(title,`<p>Copy into your coding-agent session or save locally. Review the scope and omitted references before implementation.</p><textarea class="export-text" aria-label="Agent ${esc(kind)} text" readonly></textarea><div class="actions"><button class="button" id="packet-back">Back to packet</button><button class="button primary" id="copy-agent-text">Copy text</button><button class="button" id="select-agent-text">Select all text</button></div>`);$('.export-text').value=text;
 $('#select-agent-text').onclick=()=>$('.export-text').select();$('#copy-agent-text').onclick=async()=>{try{await navigator.clipboard.writeText(text);toast('Context copied. Follow the task contract.');}catch{$('.export-text').select();toast('Text selected for copying.');}};
}
function showAgentRun(id){const r=data.agents.runs.find(x=>x.id===id);if(!r)return;modal('Agent run · '+r.task,`<p>${esc(r.owner)} · ${esc(r.state)}</p><p class="path">${esc(r.id)}</p>${r.state==='active'?`<h3 class="section-heading">Resume with a source check</h3><pre class="agent-command">python tools/workspace.py agent check ${esc(r.id)}</pre><h3 class="section-heading">Release an abandoned reservation</h3><pre class="agent-command">python tools/workspace.py agent release ${esc(r.id)} --reason "Explain why this run ended"</pre><p class="small">Release stops the reservation, not an external process. Check the owner before reassigning work.</p>`:`<pre class="reader">${esc(JSON.stringify(r.result||r,null,2))}</pre>`}`);}

function showTask(id){const w=data.work.find(x=>x.id===id);if(!w)return;modal(`${w.id} · ${w.title}`,`<p class="muted">${esc(w.question)}</p><h3 class="section-heading">Acceptance criteria</h3><ul class="criteria">${w.criteria.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><p class="small"><strong>Next action:</strong> ${esc(w.nextAction)}</p>${w.blockedBy.length?notice('Dependencies pending',w.blockedBy.join(', ')):''}<form id="work-form"><div class="form-grid"><label class="field">Workflow status<select name="status">${['ready','active','blocked','review','done'].map(s=>`<option value="${s}" ${s===w.status?'selected':''}>${labels[s]}</option>`).join('')}</select></label><label class="field">Owner<input name="owner" value="${esc(w.owner)}" maxlength="80" required></label><label class="field full">Reason for this update<textarea name="rationale" maxlength="3000" required placeholder="What changed, why, and what remains unresolved?"></textarea></label><label class="field full">Supporting evidence <small>Use Ctrl/Cmd to select several; completion requires at least one record.</small><select name="evidence" multiple>${data.snapshot.artifacts.filter(a=>['observed','verified'].includes(a.state)).map(a=>`<option value="${esc(a.id)}" ${w.evidence.includes(a.id)?'selected':''}>${esc(a.title)}</option>`).join('')}</select></label></div><p class="small">Revision ${w.revision} · This updates the local work journal. Source geometry and acceptance gates stay unchanged.</p><div class="form-error" hidden role="alert"></div><div class="form-actions"><button type="button" class="button" data-cancel>Cancel</button><button class="button primary" type="submit">Save work record</button></div></form>`);$('#work-form').addEventListener('submit',async event=>{event.preventDefault();const f=event.currentTarget,button=$('[type=submit]',f);button.disabled=true;try{await request('/api/work/'+encodeURIComponent(w.id),{expectedRevision:w.revision,expectedSnapshot:data.snapshot.id,status:f.elements.status.value,owner:f.elements.owner.value,rationale:f.elements.rationale.value,evidence:Array.from(f.elements.evidence.selectedOptions).map(o=>o.value)});await load();close();toast('Work record saved. Acceptance gates unchanged.');}catch(e){$('.form-error',f).textContent=e.message;$('.form-error',f).hidden=false;}finally{button.disabled=false;}});}
async function readArtifact(id){const a=artifact(id);if(!a)return;modal(a.title,`<p>${esc(a.scope)}</p><dl class="detail-list"><div><dt>Source / classification</dt><dd>${esc(a.member)} · ${esc(a.path)}<br>${esc(a.classification)}</dd></div><div><dt>Observed SHA-256</dt><dd class="path">${esc(a.sha256||'Unavailable')}</dd></div></dl><p>${badge(a.state)}</p><div id="source-body"><p class="small">Reading the catalogued source…</p></div>`);if(a.kind==='identity'){$('#source-body').innerHTML=notice('Identity record only','Binary assets are not served or modified. The hash identifies exact bytes; it does not certify anatomy.');return;}if(!a.href){$('#source-body').textContent='Source unavailable at the last inspection. Check the member binding and refresh.';return;}const reading=sourceRead;try{const r=await fetch(a.href);if(reading!==sourceRead||!dialog.open)return;if(!r.ok)throw new Error((await r.json()).error);if(a.kind==='image'){$('#source-body').innerHTML=`<p><a class="button" href="${esc(a.href)}" target="_blank" rel="noopener">Open original image ${icon('external')}</a></p>`;}else{const text=await r.text();if(reading!==sourceRead||!dialog.open)return;$('#source-body').innerHTML='<pre class="reader"></pre>';$('.reader').textContent=text;}}catch(e){if(reading===sourceRead&&dialog.open)$('#source-body').textContent=e.message;}}
function showObservation(){modal('Record a review observation',`<p class="muted">Record what the evidence supports, its limitations and what should be measured next. This does not record visual acceptance.</p><form id="note-form"><div class="form-grid"><label class="field">Module<select name="module">${data.catalog.modules.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select></label><label class="field">Reviewer<input name="author" maxlength="120" required></label><label class="field full">Title<input name="title" maxlength="120" required></label>${[['observation','Observation'],['limitations','Limitations / uncertainty'],['nextEvidence','Next discriminating evidence']].map(([key,label])=>`<label class="field full">${label}<textarea name="${key}" maxlength="5000" required></textarea></label>`).join('')}</div><div class="form-error" hidden role="alert"></div><div class="form-actions"><button type="button" class="button" data-cancel>Cancel</button><button class="button primary" type="submit">Save observation</button></div></form>`);$('#note-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=$('[type=submit]',form);button.disabled=true;try{await request('/api/observations',{...Object.fromEntries(new FormData(form)),expectedSnapshot:data.snapshot.id});await load();close();toast('Observation saved against '+data.snapshot.id);}catch(error){$('.form-error',form).textContent=error.message;$('.form-error',form).hidden=false;}finally{button.disabled=false;}});}
function guide(){modal('Reading the workspace',`<p>Professional terminology stays attached to its evidence. Icons and colour supplement explicit labels.</p><div class="legend"><div>${badge('verified')}<p>The inspected bytes or service identity match the named expected identity. This is not correctness or acceptance.</p></div><div>${badge('observed')}<p>The source was read at the shown time. It has an inspection hash, but no pinned expected version.</p></div><div>${badge('blocked')}<p>A dependency or unresolved question prevents that work from proceeding.</p></div><div>${badge('done')}<p>A work item has a recorded outcome and evidence. Review gates remain independent.</p></div><div>${badge('unresolved')}<p>The available evidence does not settle the interpretation.</p></div></div><h3 class="section-heading">Federation contract</h3><p>Members retain their files, Git histories and write ownership. The hub owns only local workflow records and inspection snapshots. Remote freshness and LFS ownership require separate current checks.</p><div class="actions">${sourceButton('workspace-guide','Read the operating guide')}</div>`);}
async function exportWorkspace(){try{const value=await request('/api/export');modal('Workspace export',`<p>Includes the work journal, source identities and local member paths. Review before sharing. Copy and save this JSON; no download persistence is assumed.</p><textarea class="export-text" aria-label="Workspace export JSON" readonly></textarea><button class="button" id="select-export">Select all export text</button>`);$('.export-text').value=JSON.stringify(value,null,2);$('#select-export').onclick=()=>$('.export-text').select();}catch(e){error(e.message);}}

document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.task)showTask(button.dataset.task);if(button.dataset.read)await readArtifact(button.dataset.read);if(button.dataset.cancel!==undefined)close();if(button.dataset.track){filters.track=button.dataset.track;location.hash='work';if(active==='work')render();}if(button.dataset.module){filters.module=button.dataset.module;location.hash='evidence';}if(button.dataset.runbook){const r=data.catalog.runbooks.find(x=>x.id===button.dataset.runbook);modal(r.title,runbookCard(r));}if(button.dataset.copy){const r=data.catalog.runbooks.find(x=>x.id===button.dataset.copy);try{await navigator.clipboard.writeText(r.command);toast('Command copied. Review prerequisites before running.');}catch{modal('Copy command',`<p class="small">${esc(r.title)}</p><textarea class="export-text" aria-label="Command to copy" readonly>${esc(r.command)}</textarea>`);$('.export-text').select();}}if(button.id==='add-observation')showObservation();if(button.id==='packet-back')showPacket(preparedPacket);if(button.id==='prepare-packet')await preparePacket();if(button.id==='packet-prompt')await packetText('prompt').catch(e=>error(e.message));if(button.id==='packet-json')await packetText('json');if(button.id==='packet-template')await packetText('template').catch(e=>error(e.message));if(button.dataset.agentRun)showAgentRun(button.dataset.agentRun);});
document.addEventListener('change',event=>{const id=event.target.id;if(id==='track-filter')filters.track=event.target.value;else if(id==='status-filter')filters.status=event.target.value;else if(id==='module-filter')filters.module=event.target.value;else if(id==='agent-track'){agentTrack=event.target.value;selectedAgentTask=null;}else if(id==='agent-task')selectedAgentTask=event.target.value;else return;render();$('#'+id)?.focus();});
document.addEventListener('input',event=>{if(event.target.id==='work-search'){const pos=event.target.selectionStart;filters.query=event.target.value;render();$('#work-search').focus();try{$('#work-search').setSelectionRange(pos,pos);}catch{}}});
$('#refresh').onclick=async()=>{const button=$('#refresh');button.disabled=true;try{const value=await request('/api/refresh',{});data=value;render();toast('Sources inspected. Existing work records preserved.');}catch(e){error(e.message);}finally{button.disabled=false;}};
$('#close-dialog').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});$('#guide').onclick=guide;$('#guide-mobile').onclick=guide;$('#export').onclick=exportWorkspace;
$('.skip').onclick=e=>{e.preventDefault();$('#main').focus();};
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
window.addEventListener('hashchange',route);route();load().catch(e=>error(e.message));
